object to Attribute conversion on client should not call .toString()
ldapjs/node-ldapjs pull request #711
Opened 2021-03-15 11:56 UTC by joaopbnogueira

**Bug:**
- When trying to add a binary element, such as `jpegPhoto` of type `Buffer`, the client's add method will serialize it when converting a user object to an array of attributes, which works fine for most cases, but not for binary data on Buffers.

The following pseudo-code results in an invalid image on an LDAP server
```
client.add(dn, {jpegPhoto: (buffer)});
```

Adding as an attribute works as expected:
```
const attr = new Attribute({type: 'jpegPhoto'});
attr.addValue(buffer);

client.add(dn, [attr]);
```

2021-03-15 12:10 UTC, jsumners requested changes
Please see lines 207 and 208. The documentation for this method is rather clear.

I'm sure there is room for improvement here, but an accompanying unit test would be required.

2021-03-15 15:13 UTC, joaopbnogueira commented
@jsumners  thanks for the review. 

I did not notice the method documentation, but then I guess there's the question: is the documentation the intended behavior, in which case no change should be made to the code, or is the documentation merely clarifying how it works?

2021-03-15 15:33 UTC, UziTech commented
This PR passes all of the current tests so I would say that is more of a clarification than a requirement.

2021-03-15 15:37 UTC, UziTech commented
I'm not sure how a server would handle something like a boolean or number. Perhaps we should check if it is a `Buffer` and only cast to string if it is not.

2021-03-15 16:02 UTC, jsumners commented
> This PR passes all of the current tests so I would say that is more of a clarification than a requirement.

I would argue that our tests do not currently cover the situation. A failing test should be added prior to any change to the code to illustrate the change.

2021-03-15 16:34 UTC, joaopbnogueira commented
@Y

> I'm not sure how a server would handle something like a boolean or number. Perhaps we should check if it is a `Buffer` and only cast to string if it is not.

This already happens, but on the Attribute class itself:

```
Attribute.prototype.addValue = function addValue (val) {
  if (Buffer.isBuffer(val)) {
    this._vals.push(val)
  } else {
    this._vals.push(Buffer.from(val + '', _bufferEncoding(this.type)))
  }
}
```

2021-03-15 16:38 UTC, joaopbnogueira commented
> > This PR passes all of the current tests so I would say that is more of a clarification than a requirement.
> 
> I would argue that our tests do not currently cover the situation. A failing test should be added prior to any change to the code to illustrate the change.

I'll have a look into adding a test to reproduce the bug.

2021-03-15 16:41 UTC, UziTech commented
> This already happens, but on the Attribute class itself

In that case I would say it is a bug that `client.add` casts to string.

2021-08-03 18:51 UTC, UziTech commented
I think this is fixed by #754

2021-08-04 01:54 UTC, jsumners commented
Given the lack of movement, and the potential fix going out soon, I'm closing this. If this is not resolved by the other pull request, feel free to reopen it when you have time to finish it.

2021-08-04 01:54 UTC, closed without merging

2023-03-10 13:47 UTC, jsumners commented
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.