feat: now search callback response will emit SearchRequest after every search request is sent
ldapjs/node-ldapjs pull request #730
Opened 2021-05-24 04:36 UTC by zyf0330

2021-05-24 04:37 UTC, zyf0330 commented
#728

2021-05-24 05:16 UTC, UziTech requested changes
You can run `npm run lint` to fix the linting issues.

2021-05-24 05:16 UTC, UziTech commented on docs/client.md
> +like `client.abandon` with `searchRequest.messageID` to abandon this search request. Note that the `error` event will
```suggestion
`searchRequest` is emitted immediately after every `SearchRequest` is sent with a `SearchRequest` parameter. You can do operations
like `client.abandon` with `searchRequest.messageID` to abandon this search request. Note that the `error` event will
```

2021-05-24 05:34 UTC, zyf0330 commented
> You can run `npm run lint` to fix the linting issues.

Changes have been applied.

2021-05-25 02:46 UTC, UziTech approved these changes
LGTM

2021-05-27 15:41 UTC, jsumners approved these changes
Looks good to me.

2021-05-27 19:13 UTC, merged

2023-03-10 13:46 UTC, jsumners commented
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.