Document correct connection error in client documentation
ldapjs/node-ldapjs pull request #819
Opened 2022-10-31 13:37 UTC by Tethik

When the connection fails, e.g. due to a faulty dns lookup, the `connectError` event is emitted, not `error`.

The documentation however says to listen on `error` to catch these events.
```js
client.on('error', (err) => {
  // handle connection error
})
```
Not sure if this is an error in documentation or the wrong event is used to emit an error.

https://github.com/ldapjs/node-ldapjs/blob/master/lib/client/client.js#L806-L815

2022-10-31 13:43 UTC, jsumners requested changes
Please target the `next` branch. I do not wish to deal with merge conflicts when I eventually get `next` ready.

2022-10-31 13:53 UTC, jsumners commented
Just changing the base of the PR is not enough. You'll need to rebase on the branch. It's probably easier to open a new PR starting from the branch.

2022-10-31 14:00 UTC, Tethik commented
The branch should be rebased (hence the force push)

2022-10-31 14:23 UTC, jsumners approved these changes
Looks good to me.

2022-10-31 14:23 UTC, merged

2023-03-10 13:45 UTC, jsumners commented
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.