server: prevent crash on blank DN bind
ldapjs/node-ldapjs pull request #958
Opened 2023-11-28 02:38 UTC by pulsejet

req.dn used to be parsed, now it's a string. This causes the server to crash because the assertion error cannot be trapped

2023-11-28 12:10 UTC, jsumners requested changes
Thank you for the contribution. Before we can merge it, we need a unit test added that fails without the change.

2023-11-28 18:07 UTC, pulsejet commented
Done

2023-11-30 20:50 UTC, pulsejet commented on test/server.test.js
> +          const client2 = ldap.createClient({ socketPath: t.context.sock })
It just times out. Likely an unrelated bug in the client.

2023-11-30 23:12 UTC, jsumners commented on test/server.test.js
> +          // blank bind dn but non-blank password
That acceptable in the name of clarity.

2023-12-01 07:19 UTC, pulsejet commented on test/server.test.js
> +          const client2 = ldap.createClient({ socketPath: t.context.sock })
I can replicate the same behavior in v2 so at least it isn't a regression ....

2023-12-01 07:19 UTC, pulsejet commented
Moved to a separate test

2023-12-01 14:18 UTC, jsumners commented on test/server.test.js
> +          const client2 = ldap.createClient({ socketPath: t.context.sock })
Hooray? 🤣

2023-12-01 14:20 UTC, jsumners approved these changes
Looks great. Thank you for participating in code review.

2023-12-01 14:20 UTC, merged